services:
  oracle_db:
    # A imagem que você encontrou (versão 23 slim)
    image: gvenzl/oracle-free:23-slim
    container_name: oracle_banking_db
    ports:
      - "1521:1521"
    environment:
      # A senha do admin (SYSTEM)
      - ORACLE_PASSWORD=SuaSenhaSuperSegura123
      # Usuário específico do nosso app (Opcional, mas boa prática)
      - APP_USER=banking_user
      - APP_USER_PASSWORD=banking_password
    volumes:
      # Persistência dos dados
      - ./oracle_data:/opt/oracle/oradata
    restart: always